
export const GLOSSARY: Record<string, string> = {
  // --- Architecture & Topology ---
  "Radix": "The number of ports on a switch. High radix switches (e.g., 64-port 800G) allow for flatter network topologies with fewer hops, reducing latency.",
  "Leaf-Spine": "A two-tier network topology where every leaf switch connects to every spine switch, minimizing latency and ensuring consistent bandwidth.",
  "Clos": "A multistage circuit-switching network which represents a theoretical ideal for non-blocking networks, the foundation of modern AI fabrics.",
  "Fat-Tree": "A network topology where bandwidth increases closer to the root, maintaining 1:1 subscription ratio at all levels to prevent bottlenecks.",
  "Dragonfly": "A direct-connect topology used in HPC that groups routers into groups, minimizing the diameter of the network but often requiring adaptive routing.",
  "Torus": "A ring-based topology where nodes are connected to their nearest neighbors in multiple dimensions (2D, 3D), common in traditional supercomputing.",
  "Superpod": "A cluster unit in NVIDIA architectures (e.g., 32 DGX nodes) connected via NVLink/Infiniband, representing a building block for larger AI data centers.",
  "Rail-Optimized": "A topology design where specific GPUs in a node (e.g., GPU 0) communicate with corresponding GPUs in other nodes via dedicated network rails.",
  "Non-Blocking": "A network property where any input port can be connected to any free output port without internal contention.",
  "Bisection Bandwidth": "The bandwidth available between two equal-sized partitions of a network; a key measure of network capacity for all-to-all communication.",
  "Oversubscription": "The ratio of downstream bandwidth to upstream bandwidth. AI networks typically demand 1:1 (zero oversubscription) to prevent congestion.",
  "East-West Traffic": "Network traffic flows between servers within a data center (e.g., GPU-to-GPU training), as opposed to North-South traffic (Client-to-Server).",
  "North-South Traffic": "Network traffic entering or leaving the data center (e.g., User requests to Web Server).",

  // --- Protocols & Transport ---
  "RoCE": "RDMA over Converged Ethernet. A network protocol that allows remote direct memory access over an Ethernet network, requiring a lossless fabric.",
  "RoCEv2": "Version 2 of RoCE, which encapsulates RDMA in UDP packets to enable routing across Layer 3 networks (unlike RoCEv1 which was Layer 2 only), enabling scalability across data centers.",
  "InfiniBand": "A high-speed, low-latency networking standard historically used in HPC, utilizing credit-based flow control to ensure lossless transmission.",
  "UEC": "Ultra Ethernet Consortium. An organization defining new Ethernet standards (UET) specifically optimized for AI and HPC to handle packet loss gracefully.",
  "UET": "Ultra Ethernet Transport. A next-generation transport protocol from UEC featuring packet spraying, flexible ordering, and selective recovery.",
  "TCP/IP": "Transmission Control Protocol/Internet Protocol. The backbone of the internet. Reliable but often too high-latency and CPU-intensive for internal AI fabric communication.",
  "NVMe-oF": "NVMe over Fabrics. Extending the NVMe storage protocol over networks (TCP, RoCE, FC) to access remote SSDs with local-like performance.",
  "GPUDirect": "NVIDIA technology enabling direct communication between GPUs, or between GPUs and network adapters (RDMA), bypassing the host CPU.",
  "NVLink": "A high-bandwidth, energy-efficient proprietary interconnect developed by NVIDIA for peer-to-peer GPU communication within a node or rack.",

  // --- Traffic & Congestion ---
  "PFC": "Priority Flow Control. A Layer 2 mechanism that pauses traffic for specific classes of service to prevent buffer overflow, essential for lossless Ethernet.",
  "ECN": "Explicit Congestion Notification. A Layer 3 mechanism where switches mark packets to signal incipient congestion, prompting the sender to slow down.",
  "DCQCN": "Data Center Quantized Congestion Notification. A congestion control algorithm for RoCE combining ECN and PFC concepts.",
  "Incast": "A traffic pattern where many senders communicate with a single receiver simultaneously, often causing microbursts and buffer exhaustion.",
  "Microburst": "A sudden, intense spike in traffic lasting microseconds. Too fast for SNMP polling to detect, but large enough to overflow shallow buffers.",
  "Head-of-Line Blocking": "A performance issue where a line of packets is held up by the first packet, preventing subsequent packets (even those going to other destinations) from moving.",
  "Tail Latency": "The latency experienced by the slowest percentage (e.g., 99th percentile) of requests. In AI, the tail latency defines the step time for the entire cluster.",
  "Goodput": "The number of useful information bits delivered by the network per unit of time, excluding retransmissions and protocol overhead.",
  "Packet Spraying": "A load balancing technique that distributes packets of a single flow across multiple paths simultaneously to maximize bandwidth utilization.",
  "Entropy": "Randomness introduced into packet headers (e.g., source UDP port) to help hash-based load balancers (ECMP) distribute traffic evenly.",
  "Jitter": "The variation in packet delay (latency). High jitter can disrupt synchronization in AI training collectives.",
  "ECMP": "Equal-Cost Multi-Path. A routing strategy where next-hop packet forwarding to a single destination can occur over multiple best paths.",

  // --- Hardware & Silicon ---
  "ASIC": "Application-Specific Integrated Circuit. The silicon chip inside a switch (e.g., Broadcom Tomahawk, Jericho) that performs packet forwarding logic.",
  "VOQ": "Virtual Output Queuing. A buffering architecture where packets are queued at the ingress based on their egress destination, eliminating Head-of-Line blocking.",
  "Deep Buffers": "Large memory pools (GBs) on switches/routers designed to absorb traffic bursts without dropping packets, crucial for WAN and lossless fabrics.",
  "SerDes": "Serializer/Deserializer. Functional blocks that convert parallel data to serial data for transmission over high-speed links.",
  "PAM4": "Pulse Amplitude Modulation 4-level. A modulation technique used in modern high-speed Ethernet (400G/800G) to encode two bits per symbol.",
  "LPO": "Linear Pluggable Optics. Optical modules that remove the DSP (Digital Signal Processor) to reduce power consumption and latency by up to 50%.",
  "CPO": "Co-Packaged Optics. Optics integrated directly onto the switch package substrate to maximize density and minimize electrical drive distance.",
  "SmartNIC": "A Network Interface Card with programmable compute resources (ARM cores, FPGA) to offload networking tasks (OVS, Encryption, RDMA) from the host CPU.",
  "DPU": "Data Processing Unit. An evolved SmartNIC specialized for infrastructure offloading, isolating the tenant OS from the infrastructure control plane.",
  "PCIe": "Peripheral Component Interconnect Express. A high-speed serial computer expansion bus standard for connecting GPUs, NICS, and SSDs to the host CPU.",
  "Switch Fabric": "The internal mesh of connections within a switch or router that directs traffic from input ports to output ports.",
  "Retimer": "A mixed-signal device used to extend the reach of high-speed signals by recovering the clock and regenerating the data.",
  "OSFP": "Octal Small Form-factor Pluggable. A large pluggable transceiver format used for 400G and 800G optical modules, designed for better thermal management.",
  "QSFP-DD": "Quad Small Form-factor Pluggable Double Density. A high-density transceiver module format backwards compatible with QSFP.",

  // --- AI Workloads ---
  "All-Reduce": "A collective operation where data is aggregated from all nodes (Reduce) and the result is distributed back to all nodes (Broadcast). The workhorse of LLM training.",
  "All-Gather": "A collective operation where every node gathers data from every other node, resulting in every node having a complete copy of the dataset.",
  "Scatter-Gather": "A pattern where a primary node distributes chunks of data to workers (Scatter) and collects results back (Gather).",
  "Barrier Synchronization": "A checkpoint in distributed computing where all tasks must wait until every member of the group has reached the point before any can proceed.",
  "Straggler": "A slow task, node, or link that delays the completion of a synchronized workload, causing the entire cluster to idle.",
  "Checkpointing": "The process of saving the current state of an AI model to persistent storage (NVMe/S3) so training can resume after a failure.",
  "Gradient Descent": "An optimization algorithm used to minimize the loss function in AI training by iteratively adjusting model parameters.",
  "Model Parallelism": "Splitting a single large AI model across multiple GPUs because it doesn't fit in the memory of a single device.",
  "Data Parallelism": "Replicating the entire model across multiple GPUs, where each GPU processes a different batch of training data.",
  "JCT": "Job Completion Time. The total time taken to train an AI model. In distributed training, JCT is directly impacted by network tail latency.",
  "Inference": "The phase where a trained AI model is used to generate predictions or content based on new input data.",
  "Training": "The computational process of teaching an AI model by feeding it massive datasets to adjust its internal weights.",
  "Parameter": "A configuration variable that is internal to the model and whose value can be estimated from data. LLMs have billions or trillions of parameters.",
  "Epoch": "One complete pass of the training algorithm through the entire training dataset.",
  "Batch Size": "The number of training examples utilized in one iteration.",
  "Floating Point Operations": "FLOPs. A measure of computer performance, critical for quantifying AI training compute requirements.",
  "GPU": "Graphics Processing Unit. A specialized electronic circuit designed to manipulate and alter memory to accelerate the creation of images, now the standard for AI compute.",
  "TPU": "Tensor Processing Unit. An AI accelerator application-specific integrated circuit (ASIC) developed by Google specifically for neural network machine learning.",
};
